services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "4000:4000"
    volumes:
      - backend-data:/app/backend-data
      - pfp-data:/app/pfp-data

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "4200:4000"
    depends_on:
      - api
    volumes:
      - backend-data:/app/backend-data
      - pfp-data:/app/pfp-data

volumes:
  backend-data:
  pfp-data:
